services:
  user-service:
    build: 
      context: ./user
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      HOST: postgres
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres
    depends_on:
      - db
  order-service:
    build: 
      context: ./orders
    ports:
      - "4000:4000"
    expose:
      - "4000"
    environment:
      HOST: postgres
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres
    depends_on:
      - db
  product-service:
    build: 
      context: ./products
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      HOST: postgres
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - user-service
      - order-service
      - product-service
volumes:
  local_pgdata: